# Generated by Django 5.2.1 on 2026-04-23 08:34

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0006_product_business_type'),
        ('sales', '0023_mydebt_mydebtpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_product_qty', models.PositiveIntegerField(default=1)),
                ('used_item_name', models.CharField(max_length=255)),
                ('used_item_category', models.CharField(blank=True, max_length=255)),
                ('used_item_condition', models.CharField(blank=True, max_length=255)),
                ('used_item_buying_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('addon_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_transactions', to='inventory.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_topup_transactions', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topup_transactions', to='sales.customer')),
                ('new_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_outgoing_transactions', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UsedTopupStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_category', models.CharField(blank=True, max_length=255)),
                ('condition', models.CharField(blank=True, max_length=255)),
                ('buying_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], db_index=True, default='available', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_topup_items', to='inventory.branch')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='used_stock', to='topup.topuptransaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UsedTopupSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_topup_sales', to='inventory.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_topup_purchases', to='sales.customer')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_topup_sales_created', to=settings.AUTH_USER_MODEL)),
                ('used_stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='topup.usedtopupstock')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
