# Generated by Django 5.2.1 on 2026-01-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_branch_alter_stockentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='productstock',
            options={'ordering': ['product_id', 'branch_id']},
        ),
        migrations.AlterModelOptions(
            name='stockentry',
            options={'ordering': ['-timestamp', '-id']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name']},
        ),
        migrations.AlterUniqueTogether(
            name='productstock',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(fields=('product', 'branch'), name='uniq_product_branch_stock'),
        ),
    ]
