# Generated by Django 5.2.1 on 2026-04-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_price_product_buying_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='business_type',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('magodoro', 'Magodoro'), ('unassigned', 'Unassigned')], db_index=True, default='unassigned', max_length=20),
        ),
    ]
