# Generated by Django 5.2.1 on 2026-07-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_business_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='business_type',
        ),
    ]
