# Generated by Django 5.2.1 on 2026-01-22 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_branch_alter_stockentry_options_and_more'),
        ('transport', '0002_alter_vehicle_options_driver_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_active'], name='transport_d_is_acti_333c07_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['created_at'], name='transport_d_created_58d29d_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['phone'], name='transport_d_phone_89e47a_idx'),
        ),
        migrations.AddIndex(
            model_name='transportexpense',
            index=models.Index(fields=['expense_date'], name='transport_t_expense_8d9572_idx'),
        ),
        migrations.AddIndex(
            model_name='transportexpense',
            index=models.Index(fields=['branch', 'expense_date'], name='transport_t_branch__4a8aac_idx'),
        ),
        migrations.AddIndex(
            model_name='transportexpense',
            index=models.Index(fields=['vehicle'], name='transport_t_vehicle_e171d5_idx'),
        ),
        migrations.AddIndex(
            model_name='transportexpense',
            index=models.Index(fields=['expense_type'], name='transport_t_expense_19c4f0_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['trip_date'], name='transport_t_trip_da_09bbf6_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['branch', 'trip_date'], name='transport_t_branch__d96039_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['vehicle'], name='transport_t_vehicle_0ed13b_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver'], name='transport_t_driver__1887cb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['plate_number'], name='transport_v_plate_n_6e4a6e_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_active'], name='transport_v_is_acti_d6450d_idx'),
        ),
    ]
