# Generated by Django 5.2.1 on 2026-03-13 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_price_product_buying_price_and_more'),
        ('transport', '0003_alter_driver_options_alter_driver_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=30)),
                ('pickup_area', models.CharField(max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('booking_datetime', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_bookings', to='inventory.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_bookings_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booking_datetime', '-id'],
                'indexes': [models.Index(fields=['booking_datetime'], name='transport_b_booking_76a38e_idx'), models.Index(fields=['status'], name='transport_b_status_35b5b7_idx'), models.Index(fields=['branch', 'booking_datetime'], name='transport_b_branch__6c2551_idx'), models.Index(fields=['customer_phone'], name='transport_b_custome_1d7f84_idx')],
            },
        ),
    ]
