# Generated by Django 5.2.1 on 2026-03-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportexpense',
            name='expense_type',
            field=models.CharField(choices=[('fuel', 'Fuel'), ('repair', 'Repair'), ('service', 'Service'), ('office_rent', 'Office Rent'), ('water_bill', 'Water Bill'), ('electricity', 'Electricity'), ('internet', 'Internet / Phone'), ('salary', 'Salary / Wages'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transportexpense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='transport.vehicle'),
        ),
    ]
