# Generated by Django 5.2.1 on 2026-03-13 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_price_product_buying_price_and_more'),
        ('transport', '0005_alter_transportexpense_expense_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['customer_phone'], name='transport_t_custome_7a2574_idx'),
        ),
    ]
