# Generated by Django 5.2.1 on 2025-05-14 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_invoiceitem_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Flat amount (integer) to subtract per unit'),
        ),
    ]
