# Generated by Django 5.2.1 on 2026-01-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('cash', 'Cash'), ('debt', 'Debt'), ('bank', 'Bank')], default='debt', max_length=10),
        ),
    ]
