# Generated by Django 5.2.1 on 2026-01-23 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_options_alter_product_options_and_more'),
        ('sales', '0010_expense_branch_invoice_branch_payment_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_expenses', to='inventory.branch'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(help_text='e.g. Labor, Rent, Supplies, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Sales branch where this invoice was created', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='inventory.branch'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'paid', 'created_at'], name='sales_invoi_status_415a15_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['product'], name='sales_invoi_product_6fba44_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['invoice', 'product'], name='sales_invoi_invoice_966e68_idx'),
        ),
    ]
