# Generated by Django 5.2.1 on 2026-01-24 14:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_alter_expense_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceitem',
            old_name='unit_price',
            new_name='buying_cost',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='line_cost_cache',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
