# Generated by Django 5.2.1 on 2026-01-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_delete_sale_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('ebt', 'EBT'), ('debt', 'Debt')], db_index=True, default='debt', max_length=10),
        ),
    ]
