# Generated by Django 5.2.1 on 2026-01-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_stocktransfer_stocktransferitem_branchstock_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchStock',
        ),
    ]
