# Generated by Django 5.2.1 on 2026-03-15 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_price_product_buying_price_and_more'),
        ('sales', '0020_salesreturn_salesreturnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenjiSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=150)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('item_name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('buy_date', models.DateField()),
                ('sell_date', models.DateField()),
                ('buying_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genji_sales', to='inventory.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genji_sales_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sell_date', '-id'],
            },
        ),
    ]
