# Generated by Django 5.2.1 on 2026-03-23 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_price_product_buying_price_and_more'),
        ('sales', '0021_genjisale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_state',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_state', 'created_at'], name='sales_invoi_invoice_493494_idx'),
        ),
    ]
